name: diamond-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - scikit-learn
  - optuna
  - xgboost
  - fastapi
  - uvicorn
  - streamlit
  - requests
  - pymongo
  - python-dotenv